### ISSUE TITLE
Android 64-bit support

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1598]
### Description
64-bit version for Android

### Motivation
All Google Play apps that use native code must provide a 64-bit version by August 1 in order to publish an update. https://developer.android.com/distribute/best-practices/develop/64-bit

### Requirements

- [x] Update Realm to [2.28.0](https://github.com/realm/realm-js/releases/tag/v2.28.0) or later (#1608)
- [x] Update React Native to 0.59 or later (#2012)
- [x] Update `nodejs-mobile-react-native` to 0.4.3 (#2017)

### Am I planning to do it myself with a PR?
Yes

**Comment by cvarley100** [comment]
@rajivshah3 @laumair We need to prioritise this. It's July 8th.

**Comment by rajivshah3** [comment]
Related: #1608
