### ISSUE TITLE
Quorum UI (meta-issue)

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#967]
### Description
This basically serves as a meta-issue to discuss and track progress on UI additions that should allow a user to customize how node quorum should operate. Thanks to @SleepingFox88 for the suggestions.

### Tasks

- [ ] List of available nodes for quorum (#890)
- [ ] Node blacklist (#891)
- [x] Add custom node that **may** be part of quorum (#892)
- [ ] Manual re-selection of nodes for quorum (#893)
- [x] Increase number of nodes included in quorum (#894)
- [ ] Add custom node that will **always** be part of quorum (#895)

**Comment by rajivshah3** [comment]
We might be able to combine #895 (Add custom node that will always be part of quorum) and #892 (Add custom node that may be part of quorum). When adding a node that **may** be part of the quorum, we could also have a checkbox that says something like "Always include this node in quorum"

**Comment by sloganking** [comment]
#892 and #894 are completed. Should we visually check those off on this issue?
